<nav class="navbar navbar-expand-lg menu">
	<div class="container">
		<div class="navbar-nav">
			<a class="menuItem" href="/timeline">
				Home
			</a>

			<a class="menuItem" href="/sair">
				Sair
			</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
		</div>
	</div>
</nav>
<div ng-app="myApp" ng-controller="myCtrl">
	<div class="container mt-5">
		<div class="row pt-2">

			<div class="col-md-3">

				<div class="perfil">
					<div class="perfilTopo">

					</div>

					<div class="perfilPainel">

						<div class="row mt-2 mb-2">
							<div class="col mb-2">
								<span class="perfilPainelNome"><?php
																echo $this->view->info_usuario['nome'];
																?></span>
							</div>
						</div>

						<div class="row mb-2">

							<div class="col">
								<span class="perfilPainelItem">Tweets</span><br />
								<span class="perfilPainelItemValor"><?php print_r($this->view->total_tweet['total_tweet']); ?></span>
							</div>

							<div class="col">
								<span class="perfilPainelItem">Seguindo</span><br />
								<span class="perfilPainelItemValor"><?php print_r($this->view->total_seguindo['total_seguindo']); ?></span>
							</div>

							<div class="col">

								<span class="perfilPainelItem">Seguidores</span><br />
								<a href="/seguindo">
									<span class="perfilPainelItemValor"><?php print_r($this->view->total_seguidores['total_seguidores']); ?></span>
								</a>
							</div>

						</div>

					</div>
				</div>

			</div>

			<div class="col-md-6">
				<div class="row mb-2">
					<div class="col tweetBox">
						<form method="post" action="/tweet">
							<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>

							<div class="col mt-2 d-flex justify-content-end">
								<button type="submit" class="btn btn-primary">Tweet</button>
							</div>

						</form>
					</div>
				</div>

				<div class="row tweet" ng-repeat="row in tweets">
					<div class="col">
						<p>
							<strong ng-bind="row.nome"></strong>
							<small><span class="text text-muted">{{row.data}}</span></small>
						</p>
						<p> {{ row.tweet}}</p>
						<br />
						<!-- se $value['id_usuario'] == $_SESSION['id'] -->
						<!-- div class="col d-flex justify-content-end">
								<button type="submit" class="btn btn-danger"><small>Remover</small></button>
							</div>
						</form> -->
					</div>
				</div>
			</div>

			<div class="col-md-3">
				<div class="quemSeguir">
					<span class="quemSeguirTitulo">Quem seguir</span><br />
					<hr />
					<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="/js/main.js"></script>
<script>
	angular.module('myApp', [])
		.controller('myCtrl', function($scope, $http) {
			get('tweets', 'GET', <?= $_SESSION['id'] ?>).then(function(retorno) {
				retorno = JSON.parse(retorno);
				$scope.tweets = retorno.tweets;
				$scope.$digest();
			})
		});
</script>